# Config adapted from:
# https://github.com/elastic/apm-agent-nodejs/blob/master/.travis.yml
sudo: required
dist: trusty

language: node_js

node_js:
  - '14'
  - '14.0'
  - '13'
  - '12'
  - '12.0'
  - '10'
  - '10.0'
  - '8'
  - '8.6'

git:
  depth: 1
